scrape_configs:
  - job_name: 'node_prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.0.111:9100']
  - job_name: 'node_wordpress'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.0.108:9100']
  - job_name: 'node_elk'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.0.110:9100']
  - job_name: 'node_slave'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.0.109:9100']
