#!/bin/bash

echo "Изменяем hostname VM"
hostnamectl set-hostname monitoring #название устройства
systemctl restart systemd-hostnamed #перезапускаем службу
sudo apt update
echo "Устанавливаем Docker"
sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update
apt-cache policy docker-ce
sudo apt install docker-ce
systemctl start docker #стартуем докер
systemctl enable docker #добавляем в автозагрузку
echo "Скачиваем образы Prometheus, Grafana, Node-exporter, Mysql"
docker pull -q prom/prometheus #скачивание докер-образа прометеус
docker pull -q grafana/grafana #скачивание докер-образа графаны
docker pull -q prom/node-exporter #скачивание докер-образа node-exporter
systemctl restart docker
docker run -d --restart unless-stopped -p 9100:9100 --name=node_exporter prom/node-exporter #создаем контейнер с нод-экспортером
docker run -d --restart unless-stopped -p 9090:9090 --name=prometheus -v ./prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus #создаем контейер с прометеусом
docker run -d --restart unless-stopped -p 3000:3000 --name=grafana grafana/grafana #создаем контйенер с графаной
echo "Подготовка успешно выполнена"
